services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./storage/app/public:/var/www/html/storage/app/public
      - ./.env:/var/www/html/.env:ro
